
package encryption2.encryptionapp;

import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class EncryptionApp extends javax.swing.JFrame {
    //Khoi tao 2 bien tu 2 class ma hoa
    private RC4 encrRC = new RC4();
    private TNA5 encrTN = new TNA5();
    /**
     * Creates new form NewJFrame
     */
    public EncryptionApp() {
        //Khoi tao cac phan tu trong gia dien nhu button, label,...
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKey = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPlaintext = new javax.swing.JTextArea();
        btnRC4 = new javax.swing.JButton();
        txtResult = new javax.swing.JTextField();
        btnTNA5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encrytion Tiny A5 - RC4");
        setName("Title"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Plaintext");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Key");

        txtKey.setColumns(20);
        txtKey.setRows(5);
        jScrollPane1.setViewportView(txtKey);

        txtPlaintext.setColumns(20);
        txtPlaintext.setRows(5);
        jScrollPane2.setViewportView(txtPlaintext);

        btnRC4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRC4.setText("RC4");
        btnRC4.setActionCommand("btnECR");
        btnRC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRC4ActionPerformed(evt);
            }
        });

        btnTNA5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTNA5.setText("Tiny A5");
        btnTNA5.setActionCommand("btnTNA5");
        btnTNA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTNA5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtResult)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRC4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTNA5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTNA5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRC4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Ham tuong tac khi nhan nut RC4
    private void btnRC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRC4ActionPerformed
        //Lay du lieu tu plaintext va key trong giao dien
        String text = this.txtPlaintext.getText();
        String key = this.txtKey.getText();
        //Kiem tra input plaintext co nhap dung khong
        if("Your Plainext or your key is wrong".equals(encrRC.handleEncryptncryptRC(text, key)))
        {
           //Hien thi thi box thong bao neu dau vao sai
           JOptionPane.showMessageDialog(null, "Hint: Check your Plaintext", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            //Hien thi ket qua trong text box ket qua
            this.txtResult.setText(encrRC.handleEncryptncryptRC(text, key));
        }
    }//GEN-LAST:event_btnRC4ActionPerformed

    private void btnTNA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTNA5ActionPerformed
        //Lay du lieu tu plaintext va key trong giao dien
        String text = this.txtPlaintext.getText();
        //Kiem tra input plaintext co nhap dung khong
        if("Your Plainext or your key is wrong".equals(encrTN.MaHoatinya5(text)))
        {
           //Hien thi thi box thong bao neu dau vao sai
           JOptionPane.showMessageDialog(null, "Hint: Check your Plaintext", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            //Hien thi ket qua trong text box ket qua
            this.txtResult.setText(encrTN.MaHoatinya5(text));
        }
        
    }//GEN-LAST:event_btnTNA5ActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncryptionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncryptionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncryptionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncryptionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncryptionApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRC4;
    private javax.swing.JButton btnTNA5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtKey;
    private javax.swing.JTextArea txtPlaintext;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
